app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    url(r'^ssadmin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('scheduling.urls', namespace='schedule')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduling/urls.py
from django.conf.urls import url

from scheduling.views import GaView, ProjectView, BranchAndBoundView, AddProjectView, PriorityHeuristicView, AddTaskView

urlpatterns = [
    url(r'^project/(?P<project_id>\d+)/$', ProjectView.as_view(), name='project'),
    url(r'^add_project/$', AddProjectView.as_view(), name='add_project'),
    url(r'^add_task/(?P<project_id>\d+)/$', AddTaskView.as_view(), name='add_task'),
    url(r'^ga/$', GaView.as_view(), name='ga'),
    url(r'^bab/$', BranchAndBoundView.as_view(), name='branch_and_bound'),
    url(r'^heuristic/$', PriorityHeuristicView.as_view(), name='heuristic'),
]

scheduling/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from core.models import DefaultModel, User


class Project(DefaultModel):
    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

    name = models.CharField(verbose_name='название', max_length=255)
    author = models.ForeignKey(User, verbose_name='автор')
    start_date = models.DateTimeField(verbose_name='дата начала', default=timezone.now)

    def __unicode__(self):
        return self.name


class ProjectMemberManager(models.Manager):
    def get_user_projects_ids(self, user):
        return self.filter(user=user, is_active=True).values_list('project', flat=True)

    def check_membership(self, user, project):
        return self.filter(user=user, project=project, is_active=True).first()


class ProjectMember(DefaultModel):
    TESTER = 1
    DEVELOPER = 2
    DESIGNER = 3
    MANAGER = 4

    ROLE_CHOICES = (
        (TESTER, 'Tester'),
        (DEVELOPER, 'Developer'),
        (DESIGNER, 'Designer'),
        (MANAGER, 'Manager')
    )

    class Meta:
        verbose_name = 'Участник проекта'
        verbose_name_plural = 'Участники проектов'

    user = models.ForeignKey(User, verbose_name='пользователь')
    project = models.ForeignKey(Project, verbose_name='проект')
    role = models.IntegerField(verbose_name='роль', choices=ROLE_CHOICES, default=DEVELOPER)
    is_project_admin = models.BooleanField(verbose_name='администратор проекта?', default=False)

    objects = ProjectMemberManager()

    def __unicode__(self):
        return '{0} (проект {1})'.format(self.user, self.project)


class TaskManager(models.Manager):
    def get_project_tasks(self, project_id):
        return self.filter(project_id=project_id, is_active=True)


class Task(DefaultModel):
    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    name = models.CharField(verbose_name='название', max_length=255)
    description = models.TextField(verbose_name='описание', blank=True, null=True)
    author = models.ForeignKey(User, verbose_name='автор', related_name='task_author')
    project = models.ForeignKey(Project, verbose_name='проект', related_name='task_project')
    executor = models.ForeignKey(User, verbose_name='исполнитель', related_name='task_executor', blank=True, null=True)
    executors = models.ManyToManyField(User, verbose_name='исполнители')

    start_date = models.DateTimeField(verbose_name='дата начала', default=timezone.now)
    end_date = models.DateTimeField(verbose_name='дата окончания', default=timezone.now)
    soft_deadline = models.DateTimeField(verbose_name='крайний срок (мягкий)', blank=True, null=True)
    hard_deadline = models.DateTimeField(verbose_name='крайний срок (жесткий)', blank=True, null=True)
    duration = models.FloatField(verbose_name='длительность', help_text='в часах')

    objects = TaskManager()

    def __unicode__(self):
        return self.name

    def as_dict(self):
        dic = {
            'id': self.id,
            # 'executor_id': self.executor.id,
            'executors_ids': [x.id for x in self.executors.all()],
            'duration': self.duration,
            'start_time': None,
            'end_time': None,
            's_deadline_time': (self.soft_deadline - self.project.start_date).days * 9 if self.soft_deadline else 0,
            'h_deadline_time': (self.hard_deadline - self.project.start_date).days * 9 if self.hard_deadline else 0,
            'predecessors': list(Predecessor.objects.filter(task=self).values_list('predecessor_id', flat=True)),
            'role': ProjectMember.objects.filter(user=self.executors.first()).first().role
        }
        members = ProjectMember.objects.filter(project_id=self.project_id, is_active=True, role=dic['role']).exclude(user_id=1)
        dic['demanded_count'] = len(dic['executors_ids'])
        dic['limit'] = len(members)
        return dic


class Predecessor(models.Model):
    class Meta:
        verbose_name = 'Предшественник'
        verbose_name_plural = 'Предшественники'

    task = models.ForeignKey(Task, verbose_name='основной таск')
    predecessor = models.ForeignKey(Task, verbose_name='предшественник', related_name='predecessor_task')

scheduling/forms.py
# coding=utf-8
from __future__ import unicode_literals
from django import forms

from core.models import User
from scheduling.models import Project, ProjectMember, Task


class AddProjectForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(AddProjectForm, self).__init__(*args, **kwargs)
        self.user = user

    class Meta:
        model = Project
        fields = ('name',)

    def save(self, commit=True):
        instance = super(AddProjectForm, self).save(commit=False)
        instance.author = self.user
        if commit:
            instance.save()
            membership = ProjectMember(user=self.user, project=instance, is_project_admin=True)
            membership.save()
        return instance


class AddTaskForm(forms.ModelForm):
    def __init__(self, user, project_id, *args, **kwargs):
        super(AddTaskForm, self).__init__(*args, **kwargs)
        self.user = user
        for key, field in self.fields.items():
            if key == 'executors':
                members = ProjectMember.objects.filter(is_active=True, project_id=project_id)
                field.queryset = User.objects.filter(id__in=[x.user_id for x in members])
            class_name = 'form-control'
            field.widget.attrs.update({'class': class_name})

    class Meta:
        model = Task
        fields = ('name', 'description', 'duration', 'project', 'executors')
        widgets = {'project': forms.HiddenInput()}

    def save(self, commit=True):
        instance = super(AddTaskForm, self).save(commit=False)
        instance.author = self.user
        if commit:
            print 'saving....'
            instance.save()
            self.save_m2m()
        return instance


class GeneticAlgorithmForm(forms.Form):
    probability_crossover = forms.FloatField(label='Соотношение кроссинговера к мутации', min_value=0,
                                             max_value=1)
    population_size = forms.IntegerField(label='Количество особей в популяции')
    limit = forms.IntegerField(label='Максимальное число популяций')

scheduling/views.py
# coding=utf-8
import time
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.generic import DetailView
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import FormView

from scheduling.algorithms.branch_and_bound import BranchAndBoundAlgorithm
from scheduling.algorithms.genetic_algorithm import GeneticAlgorithmSchedule
from scheduling.algorithms.helpers import ScheduleOperators
from scheduling.algorithms.heuristics import PriorityHeuristic
from scheduling.forms import GeneticAlgorithmForm, AddProjectForm, AddTaskForm
from scheduling.models import Project, Task, ProjectMember
from utils.base_views import AjaxFormView


class ProjectView(LoginRequiredMixin, DetailView):
    template_name = 'scheduling/project.html'
    model = Project
    context_object_name = 'project'
    pk_url_kwarg = 'project_id'

    def get(self, request, *args, **kwargs):
        project_id = kwargs.get('project_id', None)
        is_member = ProjectMember.objects.check_membership(request.user, project_id)
        if not is_member:
            return HttpResponseBadRequest()
        return super(ProjectView, self).get(request, *args, **kwargs)
#
# class ProjectTasksView(LoginRequiredMixin, DetailView):
#     model = Project
#     context_object_name = 'project'
#     pk_url_kwarg = 'project_id'


class AddProjectView(LoginRequiredMixin, TemplateView, AjaxFormView):
    http_method_names = ['get', 'post']
    form_class = AddProjectForm
    template_name = 'scheduling/add_project.html'

    def get_success_url(self):
        return reverse('core:profile')

    def get_form_kwargs(self):
        kwargs = super(AddProjectView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(AddProjectView, self).form_valid(form)


class AddTaskView(LoginRequiredMixin, TemplateView, AjaxFormView):
    http_method_names = ['get', 'post']
    form_class = AddTaskForm
    template_name = 'scheduling/add_task.html'
    project_id = None

    def get(self, request, *args, **kwargs):
        self.project_id = kwargs.get('project_id', None)
        is_member = ProjectMember.objects.check_membership(request.user, self.project_id)
        if not is_member:
            return HttpResponseBadRequest()
        return super(AddTaskView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('core:profile')

    def get_initial(self):
        initial = super(AddTaskView, self).get_initial()
        initial['project'] = Project.objects.filter(id=self.project_id).first()
        return initial

    def get_form_kwargs(self):
        kwargs = super(AddTaskView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['project_id'] = self.kwargs['project_id']
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(AddTaskView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AddTaskView, self).get_context_data()
        context['project_id'] = kwargs.get('project_id', None)
        return context


class GaView(FormView):
    http_method_allowed = ['post']
    project_id = None
    form_class = GeneticAlgorithmForm

    def post(self, request, *args, **kwargs):
        self.project_id = int(request.POST.get('id', None))
        is_member = ProjectMember.objects.check_membership(request.user, self.project_id)
        if not self.project_id or not is_member:
            return HttpResponseBadRequest()
        return super(GaView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        tasks = Task.objects.get_project_tasks(self.project_id)
        new_tasks = []
        for task in tasks:
            new_tasks.append(task.as_dict())
        # ToDo: добавить ошибку, если задач < 5

        probability_crossover = form.cleaned_data.get('probability_crossover')
        population_size = form.cleaned_data.get('population_size')
        limit = form.cleaned_data.get('limit')
        operators = ScheduleOperators(task_objects=new_tasks, fixed_executors=True)
        gs = GeneticAlgorithmSchedule(probability_crossover=probability_crossover, population_size=population_size,
                                      limit=limit, operators=operators)
        t_start = time.time()
        statistic = gs.run()
        t_end = time.time()
        print t_end - t_start
        return JsonResponse({'status': 'OK', 'statistic': statistic})

    def form_invalid(self, form):
        return JsonResponse({'status': 'ERROR', 'errors': {k: v for k, v in form.errors.items()}})


class BranchAndBoundView(View):
    http_method_allowed = ['post']
    project_id = None

    def post(self, request, *args, **kwargs):
        self.project_id = int(request.POST.get('id', None))
        is_member = ProjectMember.objects.check_membership(request.user, self.project_id)
        if not self.project_id or not is_member:
            return HttpResponseBadRequest()
        tasks = Task.objects.get_project_tasks(self.project_id)
        if len(tasks) > 12:
            return JsonResponse({
                'status': 'ERROR',
                'message': 'Данный метод не может обработать проект с количеством задач > 12'
            })
        new_tasks = []
        for task in tasks:
            new_tasks.append(task.as_dict())

        operators = ScheduleOperators(task_objects=new_tasks, fixed_executors=True)
        algorithm = BranchAndBoundAlgorithm(operators=operators)
        t_start = time.time()
        statistic = algorithm.run()
        t_end = time.time()
        print t_end - t_start
        return JsonResponse({
            'status': 'OK',
            'statistic': statistic,
            'show_statistic': True
        })


class PriorityHeuristicView(View):
    http_method_allowed = ['post']
    project_id = None

    def post(self, request, *args, **kwargs):
        self.project_id = int(request.POST.get('id', None))
        is_member = ProjectMember.objects.check_membership(request.user, self.project_id)
        if not self.project_id or not is_member:
            return HttpResponseBadRequest()
        tasks = Task.objects.get_project_tasks(self.project_id)
        new_tasks = []
        for task in tasks:
            new_tasks.append(task.as_dict())

        operators = ScheduleOperators(task_objects=new_tasks, fixed_executors=True)
        algorithm = PriorityHeuristic(operators=operators)
        t_start = time.time()
        statistic = algorithm.run()
        t_end = time.time()
        print t_end - t_start
        return JsonResponse({'status': 'OK', 'statistic': statistic})

scheduling/templates/scheduling/add_project.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h3>Новый проект</h3>
        <form id="js-add-project-form" class="form-horizontal" action='{% url 'schedule:add_project' %}' method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_name" class="col-2 col-form-label">Введите название</label>
                <div class="col-sm-3">
                    <input class="form-control" id="id_name" name="name">
                    <div class="form-name-error form-control-feedback"></div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
{% endblock %}

{% block body_js %}
    <script src="{% static 'scheduling/js/add_project.js' %}"></script>
{% endblock %}

scheduling/templates/scheduling/add_task.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h3>
            <a href="{% url 'schedule:project' project_id %}" style="margin-right: 10px"><img src="{% static 'core/img/back.png' %}" width="32" height="32"></a>
            Новая задача
        </h3>
        <form id="js-add-task-form" class="form-horizontal" action='{% url 'schedule:add_task' project_id %}' method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    {% if field in form.visible_fields %}
                        <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
                    {% endif %}
                    <div class="col-3">
                        {{ field }}
                        <div class="form-{{ field.name }}-error form-control-feedback"></div>
                    </div>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
{% endblock %}

{% block body_js %}
    <script src="{% static 'scheduling/js/add_task.js' %}"></script>
{% endblock %}

scheduling/templates/scheduling/project.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'core/js/libs/jsgantt/jsgantt.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Проект: {{ project.name }}</h3>

        <div class="row">
            <div class="project-left-col col-md-3">
                <div>Составить расписание:</div>
                <form class="create-schedule-form">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ project.id }}">
                    <div class="methods-list">
                        <div class="methods-list__item js-open-ga-form">Генетический алгоритм</div>
                        <div class="methods-list__item js-create-schedule"
                             data-url="{% url 'schedule:branch_and_bound' %}">
                            Метод ветвей и границ
                        </div>
                        <div class="methods-list__item js-create-schedule" data-url="{% url 'schedule:heuristic' %}">
                            Эвристика приоритетов
                        </div>

                    </div>
                </form>
                <hr>
                <div class="project-menu">
                    <a href="#" class="project-menu__item">Список задач</a>
                    <a href="{% url 'schedule:add_task' project.id %}" class="project-menu__item">Добавить задачу</a>
                </div>
            </div>

            <div class="project-right-col col-md-9">
{#                <div class="project-right-col__page project-right-col__page_active">#}
{#                    {% include 'scheduling/tasks_list.html' %}#}
{#                </div>#}
                <form class="genetic-algorithm-form hidden form-horizontal" action="{% url 'schedule:ga' %}" method='post'>
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ project.id }}">
                    <div class="form-group row">
                        <label for="prob_cross" class="col-sm-5 col-form-label">Соотношение кроссинговера к мутации</label>
                        <div class="col-sm-3">
                            <input type="number" name="probability_crossover" id="prob_cross" class="form-control"
                                   min="0" max="1" step="0.1">
                        </div>
                        <div class="col-sm-4"></div>
                    </div>
                    <div class="form-group row">
                        <label for="pop_size" class="col-sm-5 col-form-label">Количество особей в популяции</label>
                        <div class="col-sm-3">
                            <input type="number" name="population_size" id="pop_size" class="form-control">
                        </div>
                        <div class="col-sm-4"></div>
                    </div>
                    <div class="form-group row">
                        <label for="limit" class="col-sm-5 col-form-label">Максимальное число популяций</label>
                        <div class="col-sm-3">
                            <input type="number" name="limit" id="limit" class="form-control">
                        </div>
                        <div class="col-sm-4"></div>
                    </div>
                    <input type="submit" value="Запустить алгоритм">
                </form>
                <div class="statistic hidden"></div>
                <div id="GanttChartDIV" class="gantt hidden"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block body_js %}
    <script src="{% static 'core/js/libs/highcharts.js' %}"></script>
    <script src="{% static 'core/js/libs/jsgantt/jsgantt.js' %}"></script>
    <script type="text/javascript">
        var g = new JSGantt.GanttChart(document.getElementById('GanttChartDIV'), 'day');
    </script>
    <script src="{% static 'scheduling/js/project.js' %}"></script>
{% endblock %}

scheduling/templates/scheduling/tasks_list.html
{% for task in project.task_project.all %}
    {% if task.is_active %}
        <div>{{ task.name }}</div>
    {% endif %}
{% endfor %}