app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    url(r'^ssadmin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('scheduling.urls', namespace='schedule')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url

from core.views import IndexView, LoginView, RegisterView, ProfileView, LogoutView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
]

scheduling/urls.py
from django.conf.urls import url

from scheduling.views import GaView, ProjectView, BranchAndBoundView, AddProjectView, PriorityHeuristicView, AddTaskView

urlpatterns = [
    url(r'^project/(?P<project_id>\d+)/$', ProjectView.as_view(), name='project'),
    url(r'^add_project/$', AddProjectView.as_view(), name='add_project'),
    url(r'^add_task/(?P<project_id>\d+)/$', AddTaskView.as_view(), name='add_task'),
    url(r'^ga/$', GaView.as_view(), name='ga'),
    url(r'^bab/$', BranchAndBoundView.as_view(), name='branch_and_bound'),
    url(r'^heuristic/$', PriorityHeuristicView.as_view(), name='heuristic'),
]

core/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class DefaultModel(models.Model):
    class Meta:
        abstract = True

    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено в')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано в')
    is_active = models.BooleanField(default=True, verbose_name='Активно?')


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')

        if 'username' in extra_fields:
            del extra_fields['username']

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'пользователи'

    email = models.EmailField(verbose_name='Email', unique=True)
    first_name = models.CharField(verbose_name='Имя', null=True, blank=True, max_length=30)
    last_name = models.CharField(verbose_name='Фамилия', null=True, blank=True, max_length=60)
    avatar = models.ImageField(verbose_name='Аватар', upload_to='avatar', null=True, blank=True)

    is_staff = models.BooleanField(verbose_name='Персонал?', default=False)
    is_active = models.BooleanField(verbose_name='Активен?', default=False)
    date_joined = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_full_name(self):
        parts = []
        if self.first_name:
            parts.append(self.first_name)
        if self.last_name:
            parts.append(self.last_name)
        return ' '.join(parts)

    def get_short_name(self):
        return '{0}'.format(self.email)

    def __unicode__(self):
        return '{0}'.format(self.email)

    def as_dict(self):
        return {
            'id': self.id,
            'email': self.email,
            'full_name': self.get_full_name(),
            'date_joined': self.date_joined,
        }

core/forms.py
# coding=utf-8
from __future__ import unicode_literals
from django import forms
from django.core.exceptions import ValidationError

from core.models import User

NOT_THE_SAME = 'Пароль и подтверждение не совпадают'


class RegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=128, label='Пароль', widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=128, label='Подтверждение', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            class_name = 'form-control'
            field.widget.attrs.update({'class': class_name})

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password')
        confirm = cleaned_data.get('confirm')
        if password != confirm:
            raise ValidationError({'confirm': NOT_THE_SAME})
        return cleaned_data

    def save(self, commit=True):
        instance = super(RegisterForm, self).save(commit=False)
        instance.email = User.objects.normalize_email(instance.email)
        instance.set_password(instance.password)
        if commit:
            instance.save()
        return instance


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=128, label='Email')
    password = forms.CharField(max_length=128, label='Пароль', widget=forms.PasswordInput)

core/views.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.detail import DetailView

from app import settings
from core.forms import RegisterForm, LoginForm
from core.models import User
from scheduling.models import Project, ProjectMember
from utils.base_views import AjaxFormView


class IndexView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()

        return context


class LoginView(TemplateView, AjaxFormView):
    http_method_names = ['get', 'post']
    form_class = LoginForm
    template_name = 'core/login.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse('core:home'))
        return super(LoginView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if user:
            if user.is_active:
                login(self.request, user)
                return super(LoginView, self).form_valid(form)
            else:
                error_msg = 'Ваш аккаунт не активирован'
        else:
            error_msg = 'Введены неправильные email или пароль'

        return JsonResponse({
            'status': 'ERROR',
            'errors': error_msg
        })

    def get_success_url(self):
        return reverse('core:profile')


class LogoutView(RedirectView):
    http_method_names = ['get']
    pattern_name = 'core:home'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(TemplateView, AjaxFormView):
    http_method_names = ['get', 'post']
    form_class = RegisterForm
    template_name = 'core/register.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse('core:home'))
        return super(RegisterView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('core:home')

    def form_valid(self, form):
        form.save()
        # send_activation_email.delay(new_user)
        return super(RegisterView, self).form_valid(form)

#
# class ActivateView(RedirectView):
#     http_method_names = ['get']
#     pattern_name = 'core:profile'
#
#     def get(self, request, *args, **kwargs):
#         user_id = str_to_int(request.GET.get('uid'))
#         if user_id == 0:
#             return HttpResponseBadRequest()
#
#         request_token = request.GET.get('token')
#         if not request_token:
#             return HttpResponseBadRequest()
#
#         user = get_object_or_404(User, id=user_id)
#         user_token = get_activation_token(user)
#         if request_token != user_token:
#             return HttpResponseForbidden()
#
#         if not user.is_active:
#             user.is_active = True
#             user.save()
#
#         if request.user.is_anonymous():
#             user.backend = settings.AUTH_MODEL_BACKEND
#             login(request, user)
#         return super(ActivateView, self).get(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, DetailView):
    http_method_names = ['get']
    context_object_name = 'user'
    template_name = 'core/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data()
        memberships = ProjectMember.objects.get_user_projects_ids(user=self.request.user)
        context['projects'] = Project.objects.filter(id__in=memberships)
        return context

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ExecPlan</title>
    {% block css %}{% endblock %}
    {% block base_css %}
        <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    {% endblock %}

    {% block base_js %}
        <script src="{% static 'core/js/libs/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'core/js/libs/underscore-min.js' %}"></script>
        <script src="{% static 'core/js/libs/jquery.cookie.js' %}"></script>
        <script src="{% static 'core/js/common.js' %}"></script>
        <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
        <script src="https://npmcdn.com/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js"></script>
        <script src="{% static 'core/js/libs/bootstrap.min.js' %}"></script>
    {% endblock %}
    {% block js %}{% endblock %}
</head>
<body>
    {% block header %}{% include 'core/blocks/header.html' %}{% endblock %}
    {% block content %}{% endblock %}

    {% block modals %}{% endblock %}
    {% block body_js %}{% endblock %}
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container">
        <h1>Добро пожаловать!</h1>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h3>Вход</h3>
        <form id="js-login-form" class="form-horizontal" action='{% url 'core:login' %}' method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_email" class="col-1 col-form-label">Email</label>
                <div class="col-sm-3">
                    <input type="email" class="form-control" id="id_email" name="email">
                    <div class="form-email-error form-control-feedback"></div>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_password" class="col-1 col-form-label">Пароль</label>
                <div class="col-sm-3">
                    <input type="password" class="form-control" id="id_password" name="password">
                    <div class="form-password-error form-control-feedback"></div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
{% endblock %}

{% block body_js %}
    <script src="{% static 'core/js/login.js' %}"></script>
{% endblock %}

core/templates/core/profile.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-10">
                {% if projects %}
                    <h2>Выберите проект:</h2>
                    {% for project in projects %}
                        <div><a href="{% url 'schedule:project' project.id %}">{{ project.name }}</a></div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="col-2">
                <a href="{% url 'schedule:add_project' %}" class="btn btn-default">Добавить новый</a>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/register.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h3>Регистрация</h3>
        <form id="js-reg-form" class="form-horizontal" action="{% url 'core:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    {% if field in form.visible_fields %}
                        <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
                    {% endif %}
                    <div class="col-3">
                        {{ field }}
                        <div class="form-{{ field.name }}-error form-control-feedback"></div>
                    </div>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
        <h6 class="js-reg-success hidden">Регистрация прошла успешно, на укзанный адрес отправлено письмо с активацией</h6>
    </div>
{% endblock %}

{% block body_js %}
    <script src="{% static 'core/js/register.js' %}"></script>
{% endblock %}